language: objective-c
osx_image: xcode10.2

addons:
  homebrew:
    update: true
    brewfile: true

cache:
  directories:
  - buck-out/cache

before_install:
  # - rvm use $RVM_RUBY_VERSION
  - bundle install
  - gem install xcpretty-travis-formatter;
  - bundle exec pod install --repo-update;

script:
  # - buck test :yoga
  - set -o pipefail && bundle exec fastlane travis

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'FlexLayout' -J 'FlexLayoutTests'
